language: ruby
rvm: 2.2.1
script: bundle exec rake test
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - psql -c 'create database mightysmalls_test;' -U postgres
before_script:
  - bundle exec db:migrate RAILS_ENV=test