development:
  adapter: postgresql
  encoding: unicode
  database: mightysmalls_development
  pool: 5
  username: vagrant
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: mightysmalls_test
  pool: 5
  username: vagrant
  password: password